[versions]
chunky = "1.5.3"
modded = "1.4.10"

[libraries]
chunky-common = { group = "org.popcraft", name = "chunky-common", version.ref = "chunky" }
chunky-bukkit = { group = "org.popcraft", name = "chunky-bukkit", version.ref = "chunky" }
chunky-folia = { group = "org.popcraft", name = "chunky-folia", version.ref = "chunky" }
chunky-fabric = { group = "org.popcraft", name = "chunky-fabric", version.ref = "modded" }
chunky-forge = { group = "org.popcraft", name = "chunky-forge", version.ref = "modded" }
chunky-neoforge = { group = "org.popcraft", name = "chunky-neoforge", version.ref = "modded" }

dynmap = { group = "us.dynmap", name = "DynmapCoreAPI", version = "3.3" }
bluemap = { group = "com.github.BlueMap-Minecraft", name = "BlueMapAPI", version = "v2.1.0" }
squaremap = { group = "xyz.jpenilla", name = "squaremap-api", version = "1.1.2" }
pl3xmap = { group = "maven.modrinth", name = "pl3xmap", version = "1.19.4-SNAPSHOT" }

[plugins]
loom = { id = "dev.architectury.loom", version = "1.17-SNAPSHOT" }
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
shadow = { id = "com.gradleup.shadow", version = "9.6.1" }
